"""Add company_name to jobs

Revision ID: 8792187857b4
Revises: e6d077dfceec
Create Date: 2026-02-09 14:23:01.637713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8792187857b4'
down_revision: Union[str, Sequence[str], None] = 'e6d077dfceec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_link', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('company_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'company_name')
    op.drop_column('applications', 'resume_link')
    # ### end Alembic commands ###
