"""add resumes table

Revision ID: ec3180ebd4f5
Revises: d5b434aaaf41
Create Date: 2026-02-06 20:03:49.400406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3180ebd4f5'
down_revision: Union[str, Sequence[str], None] = 'd5b434aaaf41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.add_column('applications', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('applications', sa.Column('score', sa.Float(), nullable=True))
    op.alter_column('applications', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'])
    op.add_column('jobs', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('jobs', sa.Column('hr_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'users', ['hr_id'], ['id'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_column('jobs', 'hr_id')
    op.drop_column('jobs', 'description')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.alter_column('applications', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('applications', 'score')
    op.drop_column('applications', 'user_id')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
